package model.network;

public enum RequestInstruction {
	
	// LOBBY
	LOBBY_ADD_PLAYER,
	LOBBY_REMOVE_PLAYER,
	LOBBY_READY_PLAYER,
	LOBBY_CREATE,
	LOBBY_DISMANTLE,
	LOBBY_UPDATE_PLAYER,
	LOBBY_GET_PLAYER,
	LOBBY_ADD_SPECTATOR,
	LOBBY_REMOVE_SPECTATOR,
	LOBBY_ADD_BOT,
	LOBBY_REMOVE_BOT,
	LOBBY_GET_FREE_COLORS,
	
	// GAME
	GAME_CREATE,
	GAME_DISMANTLE,
	GAME_START,
	GAME_SNAPSHOT,
	GAME_DEPLOY_TROOPS,
	GAME_ATTACK,
	GAME_MOVE_TROOPS,
	GAME_TRADE_CARDS,
	GAME_PICK_CARD,
	GAME_NEXT_PHASE,
	GAME_REPLACE_WITH_BOT,
	
	// dev
	DEV_CHANGE_LOBBY_CODE,
	
	// id request
	GET_AND_INCREMENT_ID,
	
}
